In [7]:
import numpy as np
import pandas as pd


In [ ]:
#神经网络基础
1.感知机：输入多个信号，输出一个信号，权重和阈值， 与门，与非门、或门、异或门
2.激活函数是连接感知机和神经网络的桥梁，已知的激活函数： sigmoid、reLu、阶跃函数

In [2]:
#感知机的简单实现
def perceptor_and(x1,x2):
    w1,w2, theta = 0.5, 0.5, 0.7
    tmp = x1*w1 + x2*w2
    if tmp <= theta:
        return 0
    elif tmp > theta:
        return 1
    

In [5]:
perceptor_and(0,1)

0

In [8]:
#矩阵实现
x = np.array([0,1])
w = np.array([0.5,0.5])
b= -0.7
w*x

array([0. , 0.5])

In [12]:
print(np.sum(w*x) + b, np.sum(w*x), b)

-0.19999999999999996 0.5 -0.7


In [13]:
#使用权重偏置项实现
def perceptor__array_and(x1,x2):
    x = np.array([x1,x2])
    w = np.array([0.5,0.5])
    b = -0.7
    tem = np.sum(w*x) +b
    if tem <= 0:
        return 0
    else :
        return 1



神经网络的内积

In [14]:
#神经网络的矩阵实现
#X(2) W(2*3) Y(3) ndim()
X = np.array([1,2])
W = np.array([[1,3,5],[2,4,6]])
Y = np.dot(X, W)
print(X, W, Y)


[1 2] [[1 3 5]
 [2 4 6]] [ 5 11 17]


#3层神经网络的实现
#2-3-2-2全连接网络
a1(1) = x1*w11(1) + x2*w12(1) + b1(1)
A(1) = X*W + B
其中A(1) = [a1,a2,a3]
X = [x1, x2]
B = [b1(1), b2(1), b3(1)]
W = [[w11(1),w12(1),w13(1)],
    [w21(1),w22(1),w23(1)]]

In [15]:
X = np.array([1, 0.5])
W1 = np.array([[0.1, 0.3, 0.5],[0.2, 0.4, 0.6]])
B1 = np.array([0.1, 0.2, 0.3])

print(W1.shape, X.shape, B1.shape)

(2, 3) (2,) (3,)


In [19]:
A1 = npL.dot(X,W1) + B1.T

In [20]:
A1

array([0.3, 0.7, 1.1])