In [7]:
import numpy as np
import pandas as pd


In [ ]:
#神经网络基础
1.感知机：输入多个信号，输出一个信号，权重和阈值， 与门，与非门、或门、异或门
2.激活函数是连接感知机和神经网络的桥梁，已知的激活函数： sigmoid、reLu、阶跃函数

In [2]:
#感知机的简单实现
def perceptor_and(x1,x2):
    w1,w2, theta = 0.5, 0.5, 0.7
    tmp = x1*w1 + x2*w2
    if tmp <= theta:
        return 0
    elif tmp > theta:
        return 1
    

In [5]:
perceptor_and(0,1)

0

In [8]:
#矩阵实现
x = np.array([0,1])
w = np.array([0.5,0.5])
b= -0.7
w*x

array([0. , 0.5])

In [12]:
print(np.sum(w*x) + b, np.sum(w*x), b)

-0.19999999999999996 0.5 -0.7


In [13]:
#使用权重偏置项实现
def perceptor__array_and(x1,x2):
    x = np.array([x1,x2])
    w = np.array([0.5,0.5])
    b = -0.7
    tem = np.sum(w*x) +b
    if tem <= 0:
        return 0
    else :
        return 1



神经网络的内积

In [14]:
#神经网络的矩阵实现
#X(2) W(2*3) Y(3) ndim()
X = np.array([1,2])
W = np.array([[1,3,5],[2,4,6]])
Y = np.dot(X, W)
print(X, W, Y)


[1 2] [[1 3 5]
 [2 4 6]] [ 5 11 17]


In [21]:
#三个激活函数
def sigmoid(x):
    return 1/(1 + np.exp(-x))
def ste_function(x):
     y = x>0
     return y.astype(np.int)
def relu(x):
    return np.maximum(0,x)

#3层神经网络的实现
#2-3-2-2全连接网络
a1(1) = x1*w11(1) + x2*w12(1) + b1(1)
A(1) = X*W + B
其中A(1) = [a1,a2,a3]
X = [x1, x2]
B = [b1(1), b2(1), b3(1)]
W = [[w11(1),w12(1),w13(1)],
    [w21(1),w22(1),w23(1)]]

In [15]:
X = np.array([1, 0.5])
W1 = np.array([[0.1, 0.3, 0.5],[0.2, 0.4, 0.6]])
B1 = np.array([0.1, 0.2, 0.3])

print(W1.shape, X.shape, B1.shape)

(2, 3) (2,) (3,)


In [19]:
A1 = npL.dot(X,W1) + B1.T

In [20]:
A1

array([0.3, 0.7, 1.1])

In [22]:
Z1 = sigmoid(A1)
Z1

array([0.57444252, 0.66818777, 0.75026011])

In [24]:
#下面实现第一层到第二层的信号传递
W2 = np.array([[0.1, 0.4],[0.2, 0.5],[0.3, 0.6]])
B2 = np.array([0.1, 0.2])
print(Z1.shape)
print(W2.shape)
print(B2.shape)

(3,)
(3, 2)
(2,)


In [25]:
A2 = np.dot(Z1, W2) + B2
Z2 = sigmoid(A2)
print(Z2)

[0.62624937 0.7710107 ]


In [26]:
def identity_function(x):
    return x
W3 = np.array([[0.1, 0.3], [0.2, 0.4]])
B3 = np.array([0.1, 0.2])
A3 = np.dot(Z2, W3) + B3
Y = identity_function(A3) # 或者Y = A3

In [32]:
print(Y)

[0.31682708 0.69627909]


In [30]:
#代码实现小结
def init_network():
    network = {}
    network['W1'] = np.array([[0.1, 0.3, 0.5],[0.2,0.4, 0.6]])
    network['b1'] = np.array([0.1, 0.2, 0.3])
    network['W2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
    network['b2'] = np.array([0.1, 0.2])
    network['W3'] = np.array([[0.1, 0.3], [0.2, 0.4]])
    network['b3'] = np.array([0.1, 0.2])
    return network
def forward(network,x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']

    a1 = np.dot(x, W1)+ b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2)+ b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, W3)+ b3
    y = identity_function(a3)
    return y


In [31]:
network = init_network()
x = np.array([1, 0.5])
y = forward(network, x)
print(y)

[0.31682708 0.69627909]


输出层的设计

#恒等函数和softmax函数
分类与回归，回归用恒等函数，多分类用softmax函数(输出所有的类别概率值)

In [33]:
def softmax(a):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    y = exp_a/sum_exp_a
    return y


In [35]:
np.exp(1000) 溢出问题

inf

In [36]:
def softmax_new(a):
    c = np.max(a)
    exp_a = np.exp(a-c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a /sum_exp_a

    return y

In [37]:
a = np.array([0.3, 2.9, 4.0])
y = softmax(a)
print(y)

[0.01821127 0.24519181 0.73659691]


In [38]:
np.sum(y)

1.0

手写识别数据

In [48]:
import sys,os
sys.path.append(os.pardir) # 为了导入父目录中的文件而进行的设定
from dataset import mnist 

ImportError: cannot import name 'mnist'

数据加载+交叉熵损失函数+mini_bacth

In [47]:
from dataset.mnist import load_mnist

ModuleNotFoundError: No module named 'dataset.mnist'

In [51]:
pip install mnist


Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Note: you may need to restart the kernel to use updated packages.
