In [4]:
import gluonbook as gb
from mxnet import nd


In [17]:
def corr2d_multi_in(X, K):
    #沿着X和K的第0维通道维遍历。然后使用*将结果列表变成add_n函数的位置参数（positional argument)来进行相加
    #for  x, k in zip(X, K):
      #  print(x,k)
    return nd.add_n(*[gb.corr2d(x, k) for x, k in zip(X, K)])

In [6]:
X = nd.array([[[0, 1, 2], [3, 4, 5], [6, 7, 8]],[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
K = nd.array([[[0, 1], [2, 3]], [[1, 2], [3, 4]]])

In [7]:
corr2d_multi_in(X,K)


[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
<NDArray 3x3 @cpu(0)> 
[[0. 1.]
 [2. 3.]]
<NDArray 2x2 @cpu(0)>

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
<NDArray 3x3 @cpu(0)> 
[[1. 2.]
 [3. 4.]]
<NDArray 2x2 @cpu(0)>



[[ 56.  72.]
 [104. 120.]]
<NDArray 2x2 @cpu(0)>

5.3.2 多输出通道

In [8]:
def corr2d_multi_in_out(X, K):
    # 对K 的第0 维遍历，每次同输⼊X 做互相关计算。所有结果使⽤stack 函数合并在⼀起。
    return nd.stack(*[corr2d_multi_in(X, k) for k in K])

In [9]:
K = nd.stack(K, K + 1, K + 2)
K


[[[[0. 1.]
   [2. 3.]]

  [[1. 2.]
   [3. 4.]]]


 [[[1. 2.]
   [3. 4.]]

  [[2. 3.]
   [4. 5.]]]


 [[[2. 3.]
   [4. 5.]]

  [[3. 4.]
   [5. 6.]]]]
<NDArray 3x2x2x2 @cpu(0)>

In [10]:
K.shape

(3, 2, 2, 2)

In [11]:
corr2d_multi_in_out(X, K)


[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
<NDArray 3x3 @cpu(0)> 
[[0. 1.]
 [2. 3.]]
<NDArray 2x2 @cpu(0)>

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
<NDArray 3x3 @cpu(0)> 
[[1. 2.]
 [3. 4.]]
<NDArray 2x2 @cpu(0)>

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
<NDArray 3x3 @cpu(0)> 
[[1. 2.]
 [3. 4.]]
<NDArray 2x2 @cpu(0)>

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
<NDArray 3x3 @cpu(0)> 
[[2. 3.]
 [4. 5.]]
<NDArray 2x2 @cpu(0)>

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
<NDArray 3x3 @cpu(0)> 
[[2. 3.]
 [4. 5.]]
<NDArray 2x2 @cpu(0)>

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
<NDArray 3x3 @cpu(0)> 
[[3. 4.]
 [5. 6.]]
<NDArray 2x2 @cpu(0)>



[[[ 56.  72.]
  [104. 120.]]

 [[ 76. 100.]
  [148. 172.]]

 [[ 96. 128.]
  [192. 224.]]]
<NDArray 3x2x2 @cpu(0)>

In [12]:
def corr2d_multi_in_out_1x1(X, K):
    c_i, h, w = X.shape
    c_o = K.shape[0]
    X = X.reshape((c_i, h*w ))
    K  = K.reshape(c_o, c_i)
    Y = nd.dot(K,X)
    return Y.reshape((c_o, h, w))

In [13]:
X = nd.random.uniform(shape = (3,3,3))
K = nd.random.uniform(shape = (2,3,1,1))


In [14]:
X


[[[0.5488135  0.5928446  0.71518934]
  [0.84426576 0.60276335 0.8579456 ]
  [0.5448832  0.8472517  0.4236548 ]]

 [[0.6235637  0.6458941  0.3843817 ]
  [0.4375872  0.2975346  0.891773  ]
  [0.05671298 0.96366274 0.2726563 ]]

 [[0.3834415  0.47766513 0.79172504]
  [0.8121687  0.5288949  0.47997716]
  [0.56804454 0.3927848  0.92559665]]]
<NDArray 3x3x3 @cpu(0)>

In [15]:
K


[[[[0.83607876]]

  [[0.07103606]]

  [[0.33739617]]]


 [[[0.08712929]]

  [[0.6481719 ]]

  [[0.0202184 ]]]]
<NDArray 2x3x1x1 @cpu(0)>

In [16]:
Y1 = corr2d_multi_in_out_1x1(X, K)
Y2 = corr2d_multi_in_out(X, K)


[[0.5488135  0.5928446  0.71518934]
 [0.84426576 0.60276335 0.8579456 ]
 [0.5448832  0.8472517  0.4236548 ]]
<NDArray 3x3 @cpu(0)> 
[[0.83607876]]
<NDArray 1x1 @cpu(0)>

[[0.6235637  0.6458941  0.3843817 ]
 [0.4375872  0.2975346  0.891773  ]
 [0.05671298 0.96366274 0.2726563 ]]
<NDArray 3x3 @cpu(0)> 
[[0.07103606]]
<NDArray 1x1 @cpu(0)>

[[0.3834415  0.47766513 0.79172504]
 [0.8121687  0.5288949  0.47997716]
 [0.56804454 0.3927848  0.92559665]]
<NDArray 3x3 @cpu(0)> 
[[0.33739617]]
<NDArray 1x1 @cpu(0)>

[[0.5488135  0.5928446  0.71518934]
 [0.84426576 0.60276335 0.8579456 ]
 [0.5448832  0.8472517  0.4236548 ]]
<NDArray 3x3 @cpu(0)> 
[[0.08712929]]
<NDArray 1x1 @cpu(0)>

[[0.6235637  0.6458941  0.3843817 ]
 [0.4375872  0.2975346  0.891773  ]
 [0.05671298 0.96366274 0.2726563 ]]
<NDArray 3x3 @cpu(0)> 
[[0.6481719]]
<NDArray 1x1 @cpu(0)>

[[0.3834415  0.47766513 0.79172504]
 [0.8121687  0.5288949  0.47997716]
 [0.56804454 0.3927848  0.92559665]]
<NDArray 3x3 @cpu(0)> 
[[0.0202184]]
<NDA