In [11]:
import numpy as np
import pandas as pd


#神经网络基础
1.感知机：输入多个信号，输出一个信号，权重和阈值， 与门，与非门、或门、异或门
2.激活函数是连接感知机和神经网络的桥梁，已知的激活函数： sigmoid、reLu、阶跃函数

In [13]:
#感知机的简单实现
def perceptor_and(x1,x2):
    w1,w2, theta = 0.5, 0.5, 0.7
    tmp = x1*w1 + x2*w2
    if tmp <= theta:
        return 0
    elif tmp > theta:
        return 1
    

In [14]:
perceptor_and(0,1)

0

In [15]:
#矩阵实现
x = np.array([0,1])
w = np.array([0.5,0.5])
b= -0.7
w*x

array([0. , 0.5])

In [16]:
print(np.sum(w*x) + b, np.sum(w*x), b)

-0.19999999999999996 0.5 -0.7


In [17]:
#使用权重偏置项实现
def perceptor__array_and(x1,x2):
    x = np.array([x1,x2])
    w = np.array([0.5,0.5])
    b = -0.7
    tem = np.sum(w*x) +b
    if tem <= 0:
        return 0
    else :
        return 1



神经网络的内积

In [18]:
#神经网络的矩阵实现
#X(2) W(2*3) Y(3) ndim()
X = np.array([1,2])
W = np.array([[1,3,5],[2,4,6]])
Y = np.dot(X, W)
print(X, W, Y)


[1 2] [[1 3 5]
 [2 4 6]] [ 5 11 17]


In [19]:
#三个激活函数
def sigmoid(x):
    return 1/(1 + np.exp(-x))
def ste_function(x):
     y = x>0
     return y.astype(np.int)
def relu(x):
    return np.maximum(0,x)

#3层神经网络的实现
#2-3-2-2全连接网络
a1(1) = x1*w11(1) + x2*w12(1) + b1(1)
A(1) = X*W + B
其中A(1) = [a1,a2,a3]
X = [x1, x2]
B = [b1(1), b2(1), b3(1)]
W = [[w11(1),w12(1),w13(1)],
    [w21(1),w22(1),w23(1)]]

In [20]:
X = np.array([1, 0.5])
W1 = np.array([[0.1, 0.3, 0.5],[0.2, 0.4, 0.6]])
B1 = np.array([0.1, 0.2, 0.3])

print(W1.shape, X.shape, B1.shape)

(2, 3) (2,) (3,)


In [22]:
A1 = np.dot(X,W1) + B1.T

In [23]:
A1

array([0.3, 0.7, 1.1])

In [24]:
Z1 = sigmoid(A1)
Z1

array([0.57444252, 0.66818777, 0.75026011])

In [25]:
#下面实现第一层到第二层的信号传递
W2 = np.array([[0.1, 0.4],[0.2, 0.5],[0.3, 0.6]])
B2 = np.array([0.1, 0.2])
print(Z1.shape)
print(W2.shape)
print(B2.shape)

(3,)
(3, 2)
(2,)


In [26]:
A2 = np.dot(Z1, W2) + B2
Z2 = sigmoid(A2)
print(Z2)

[0.62624937 0.7710107 ]


In [27]:
def identity_function(x):
    return x
W3 = np.array([[0.1, 0.3], [0.2, 0.4]])
B3 = np.array([0.1, 0.2])
A3 = np.dot(Z2, W3) + B3
Y = identity_function(A3) # 或者Y = A3

In [28]:
print(Y)

[0.31682708 0.69627909]


In [29]:
#代码实现小结
def init_network():
    network = {}
    network['W1'] = np.array([[0.1, 0.3, 0.5],[0.2,0.4, 0.6]])
    network['b1'] = np.array([0.1, 0.2, 0.3])
    network['W2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
    network['b2'] = np.array([0.1, 0.2])
    network['W3'] = np.array([[0.1, 0.3], [0.2, 0.4]])
    network['b3'] = np.array([0.1, 0.2])
    return network
def forward(network,x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']

    a1 = np.dot(x, W1)+ b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2)+ b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, W3)+ b3
    y = identity_function(a3)
    return y


In [30]:
network = init_network()
x = np.array([1, 0.5])
y = forward(network, x)
print(y)

[0.31682708 0.69627909]


输出层的设计

#恒等函数和softmax函数
分类与回归，回归用恒等函数，多分类用softmax函数(输出所有的类别概率值)

In [31]:
def softmax(a):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    y = exp_a/sum_exp_a
    return y


In [32]:
np.exp(1000) #溢出问题

inf

In [33]:
def softmax_new(a):
    c = np.max(a)
    exp_a = np.exp(a-c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a /sum_exp_a

    return y

In [34]:
a = np.array([0.3, 2.9, 4.0])
y = softmax(a)
print(y)

[0.01821127 0.24519181 0.73659691]


In [35]:
np.sum(y)

1.0

手写识别数据

In [36]:
import sys,os
sys.path.append(os.pardir) # 为了导入父目录中的文件而进行的设定
from dataset import mnist 

数据加载+交叉熵损失函数+mini_bacth

In [40]:
from dataset.mnist import load_mnist  #此dataset是深度学习入门基于python的源码文件
(x_train, t_train), (x_test, t_test) = load_mnist(flatten=True,
normalize=False)
print(x_train.shape)

Done
Done
Done
Done
Converting train-images-idx3-ubyte.gz to NumPy Array ...
Done
Converting train-labels-idx1-ubyte.gz to NumPy Array ...
Done
Converting t10k-images-idx3-ubyte.gz to NumPy Array ...
Done
Converting t10k-labels-idx1-ubyte.gz to NumPy Array ...
Done
Creating pickle file ...
Done!
(60000, 784)


In [49]:
from PIL import Image
def img_show(img):
    pil_img = Image.fromarray(np.uint8(img))
    pil_img.show()
(x_train, t_train), (x_test, t_test) = load_mnist(flatten=True,normalize=False)
img = x_train[0]
label = t_train[0]
print(label) # 5
print(img.shape) # (784,)
img = img.reshape(28, 28) # 把图像的形状变成原来的尺寸
print(img.shape) # (28, 28)
img_show(img)   

5
(784,)
(28, 28)


Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
     |████████████████████████████████| 2.2 MB 30.0 MB/s 
Note: you may need to restart the kernel to use updated packages.


In [68]:
sys.path.append('os.pardir')
import pickle
def get_data():
    (x_train, t_train), (x_test, t_test) = \
    load_mnist(normalize=True, flatten=True, one_hot_label=False)
    return x_test, t_test
def init_network():
    with open("../ch03/sample_weight.pkl", 'rb') as f:
        network = pickle.load(f)
    return network
def predict(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']

    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, W3) + b3
    y = softmax(a3)
    return y

In [69]:
x, t = get_data()
network = init_network()
accuracy_cnt = 0
for i in range(len(x)):
    y = predict(network, x[i])
    p = np.argmax(y) # 获取概率最高的元素的索引
    if p == t[i]:
        accuracy_cnt += 1
print("Accuracy:" + str(float(accuracy_cnt) / len(x)))

Accuracy:0.9352


In [70]:
x, t = get_data()
network = init_network()
batch_size = 100 # 批数量
accuracy_cnt = 0
for i in range(0, len(x), batch_size):
    x_batch = x[i:i+batch_size]
    y_batch = predict(network, x_batch)
    p = np.argmax(y_batch, axis=1)
    accuracy_cnt += np.sum(p == t[i:i+batch_size])
print("Accuracy:" + str(float(accuracy_cnt) / len(x)))

Accuracy:0.9352


数据加载+交叉熵损失函数+mini_bacth

In [71]:
train_size = x_train.shape[0]
batch_size = 10
batch_mask = np.random.choice(train_size, batch_size)
x_batch = x_train[batch_mask]
t_batch = t_train[batch_mask]

In [72]:
batch_mask

array([37293, 58568, 52300, 24812, 35571, 54107, 45056, 59889,  7891,
       20290])

In [79]:
#y为一个样本的10个类别输出，t为类别的one-hot编码
def cross_entropy_error(y,t):
    if y.ndim ==1:
        t = t.reshape(1,t.size)
        y = y.reshape(1, y.size)
    batch_size = y.shape(0)
    return -np.sum(t*np.log(y + 1e-7))/batch_size

In [80]:
#mini_batch y为批量样本多维输出, t为批量样本的类别
def cross_entropy_error(y, t):
    if y.ndim == 1:
        print(y)
        t = t.reshape(1,t.size)  #一行
        y = y.reshape(1, y.size)
    batch_size = y.shape(0)
    print(y)
    print(y[np.arange(batch_size), t])
    return -np.sum(np.log(y[np.arange(batch_size), t] + 1e-7)) / batch_size


(60000, 784)

In [83]:
[np.arange(5),[5,4,4,1,2]]

[array([0, 1, 2, 3, 4]), [5, 4, 4, 1, 2]]